---
- hosts: switches
  gather_facts: no
  
  vars:
    ansible_connection: ansible.netcommon.network_cli
    ansible_network_os: community.network.routeros
    ansible_port: "{{ global_ssh_port }}"
    ansible_user: mikrotikuser

  tasks:
    - name: Include bridge tasks
      ansible.builtin.import_tasks:
        file: tasks/bridge.yaml
      tags:
        - bridge
        - switch
