---
    - name: Set ssh port
      community.routeros.command:
        commands:
          - /ip service set ssh port={{ global_ssh_port }}
      when:
        - global_ssh_port is defined

    - name: Set ssh port
      community.routeros.command:
        commands:
          - /ip service set winbox port={{ global_winbox_port }}
      when:
        - global_winbox_port is defined

    - name: Add DNS servers
      community.routeros.command:
        commands:
          - /ip dns set servers={{ global_dns_server }}
      when:
        - global_dns_server is defined

    - name: Add identity
      community.routeros.command:
        commands:
          - /system identity set name="{{ inventory_hostname }}"

    - name: Configure device security
      community.routeros.command:
        commands:
          - /ip service disable api,api-ssl,ftp,telnet,www
          - /ip ssh set always-allow-password-login=yes

    - name: Configure snmp
      community.routeros.command:
        commands:
          - /snmp set contact={{ group_snmp_contact }} enabled=yes location={{ group_snmp_location }} trap-version=2
      when:
        - group_snmp_contact is defined
        - group_snmp_location is defined

    - name: Set ssh and winbox access ip range
      community.routeros.command:
        commands:
          - /ip service set winbox,ssh address={{ global_ssh_winbox_access }}
      when:
        - global_ssh_winbox_access is defined

    - name: Set timezone
      community.routeros.command:
        commands:
          - /system clock set time-zone-name={{ global_timezone }}
      when:
        - global_timezone is defined

    - name: Set ntp
      community.routeros.command:
        commands:
          - /system ntp client set enabled=yes
          - /system ntp client servers add address={{ global_ntp_server }}
      when:
        - global_ntp_server is defined
